org: rolandodiaz
service: api-productos

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::409362080365:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_productos
    JWT_SECRET: mi-super-secreto-jwt-2025

functions:
  listar-productos:
    handler: productos.listarProductos
    events:
      - http:
          path: /productos/listar
          method: get
          cors: true
          integration: lambda

  crear-producto:
    handler: productos.crearProducto
    events:
      - http:
          path: /productos/crear
          method: post
          cors: true
          integration: lambda

  buscar-producto:
    handler: productos.buscarProducto
    events:
      - http:
          path: /productos/buscar/{codigo}
          method: get
          cors: true
          integration: lambda

  modificar-producto:
    handler: productos.modificarProducto
    events:
      - http:
          path: /productos/modificar/{codigo}
          method: put
          cors: true
          integration: lambda

  eliminar-producto:
    handler: productos.eliminarProducto
    events:
      - http:
          path: /productos/eliminar/{codigo}
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    TablaProductos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: codigo
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: codigo
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES